### ISSUE TITLE
localization error

### ISSUE THREAD

**Issue by wangtao03** [PaulSquires/WinFBE#1]
frmCompileConfig.inc 
Line 404:  pWindow->Create(hWndParent, rtrim(AfxStrRemove(L(277,"&Build Configurations..."), "&"),"."), _

frmRecent.inc
Line 29:    wzStr = UCase(AfxStrRemove( L(10, "&Recent Files"), "&")) 
Line 51:    wzStr = UCase(AfxStrRemove( L(219, "&Recent Projects"), "&")) 

modRoutines.inc
Line 780:          hr = psfd->lpVtbl->SetTitle(psfd, AfxStrRemove(L(185,"Save Project &As..."),"&"))
Line 790:          psfd->lpVtbl->SetTitle(psfd, AfxStrRemove(L(265,"Save &Declares File"),"&"))
Line 802:          psfd->lpVtbl->SetTitle(psfd, AfxStrRemove(L(8,"Save &As..."),"&"))

use chinese
00008:另存为(&A)...
00010:最近打开的文件(&R)
00185:工程另存为(&A)...
00219:最近打开的工程(&R)
00265:保存声明文件(&D)...
00277:构建配置(&B)...

will cause the form to stop responding.error in format "(&A)"

**Comment by PaulSquires** [comment]
Please try Version 1.5.3 and post reply if issue is now fixed. Thanks!

**Comment by wangtao03** [comment]
thank you
error was fixed!
[http://www.mediafire.com/file/s5xz2a4g56i6yos/chinese.lang](url)
this is chinese language file

**Comment by PaulSquires** [comment]
Excellent - thanks for letting me know and thank-you for the chinese language file!
