### ISSUE TITLE
New chinese.lang, Please update.

### ISSUE THREAD

**Issue by sir2k** [PaulSquires/WinFBE#12]
I translate the newest chinese.lang file. Please update it.

filename: chinese.lang 
contents:
======================================

' WinFBE localization file for CHINESE language
'
' The first element to exist must be called "MAXIMUM" and needs to be set to
' the value of the last key in this file. 
'
' This file should be created and saved using UTF-16 (BOM) encoding (unicode).
'  
' Each line represents a key/value pair describing the position to store the
' localized word/phrase into the localization array used by WinFBE. Simple.

MAXIMUM:400

00000:确定(&O)
00001:取消(&C)
00002:文件(&F)
00003:新建(&N)
00004:打开...(&O)
00005:关闭(&C)
00006:关闭全部(&L)
00007:保存(&S)
00008:另存为...
00009:全部保存
00010:最近的文件
00011:(空)
00012:命令提示符...(&M)
00013:退出(&X)
00014:编辑(&E)
00015:撤销(&U)
00016:重做(&R)
00017:剪切(&T)
00018:复制(&C)
00019:粘贴(&P)
00020:删除行(&D)
00021:插入文件...(&F)
00022:区块操作(&B)
00023:区块缩进(&I)
00024:取消区块缩进(&N)
00025:区块注释(&M)
00026:取消区块注释(&B)
00027:行操作(&L)
00028:重复当前行(&D)
00029:上移当前行(&U)
00030:下移当前行(&D)
00031:转换选区内容为(&C)
00032:大写(&E)
00033:小写(&L)
00034:首字母大写(&X)
00035:转换行尾字符为(&E)
00036:回车换行符
00037:回车符
00038:换行符
00039:替换制表符为空格(&W)
00040:选择全部(&A)
00041:选择行(&S)
00042:搜索(&S)
00043:查找...(&F)
00044:查找下一个
00045:查找上一个
00046:替换...
00047:过程/函数定义(&D)
00048:最后位置(&L)
00049:行跳转...(&G)
00050:切换书签(&T)
00051:下一个书签(&B)
00052:上一个书签(&V)
00053:清除书签(&C)
00054:视图(&V)
00055:切换折叠/展开(&C)
00056:切换折叠/展开至末尾(&B)
00057:折叠全部(&A)
00058:展开全部(&U)
00059:放大(&I)
00060:缩小(&O)
00061:恢复主窗口大小(&R)
00062:环境选项...(&V)
00063:项目(&P)
00064:编译(&C)
00065:编译并运行(&X)
00066:编译(&C)
00067:运行(&R)
00068:命令行(&L)
00069:使用32位编译器
00070:使用64位编译器
00071:编译GUI应用程序
00072:编译控制台应用程序
00073:帮助(&H)
00074:关于(&A)
00075:打开
00076:保存当前更改?
00077:代码文件
00078:头文件
00079:所有文件
00080:插入文件
00081:未找到文件
00082:下一个
00083:上一个
00084:下一个函数
00085:上一个函数
00086:关闭
00087:你确认要删除这个代码片段？
00088:用户代码片段集
00089:触发器
00090:在代码编辑器中按Tab键以激活
00091:检查更新
00092:无法获取更新信息
00093:错误
00094:软件更新
00095:启用自动完成
00096:已经更新为最新版
00097:是当前最新可用版本。
00098:有新版本！
00099:当前
00100:FB编译器
00101:查找FreeBASIC编译器
00102:本地化文件
00103:打开本地化文件
00104:帮助文件
00105:查找帮助文件
00106:打开源文件
00107:有效
00108:下一次运行应用程序时将应用本地化更改。
00109:警告
00110:代码编辑器
00111:颜色和字体
00112:编译设置
00113:环境选项
00114:语法高亮显示
00115:启用代码提示
00116:光标限于文本
00117:高亮当前行
00118:制表符TAB作为空格处理
00119:允许多个实例
00120:自动缩进
00121:编译前自动保存文件
00122:显示左边间距
00123:显示折叠区
00124:显示行号
00125:显示缩进指示虚线
00126:选择
00127:Tab键缩进大小
00128:大小写
00129:本地化
00130:小写
00131:大写
00132:原始大小写
00133:颜色集
00134:颜色
00135:背景
00136:字体(适用于所有样式)
00137:打开下载网站？
00138:光标
00139:注释
00140:高亮的行
00141:关键词
00142:折叠区
00143:折叠符号
00144:缩进指示虚线
00145:行号
00146:操作符
00147:预处理器
00148:选区
00149:字符串
00150:文本
00151:适配宽度
00152:窗口
00153:附加编译选项开关(可选)
00154:FBC 32位编译器
00155:FreeBASIC帮助文件(* .chm)
00156:FBC 64位编译器
00157:WinAPI帮助文件(Win32_fb.chm)
00158:查找
00159:查找内容
00160:适配高度
00161:关闭
00162:整个单词匹配
00163:大小写匹配
00164:适用范围
00165:使用高分辨率缩放
00166:启动时检查更新（1次/天）
00167:选项
00168:转到行
00169:最后一行
00170:当前行
00171:跳转行
00172:（使用鼠标右击弹出菜单选项以插入参数）
00173:替换
00174:全部替换
00175:头
00176:模板
00177:FreeBASIC关键字
00178:命令行
00179:输入命令行参数
00180:新的项目(&N)
00181:头文件
00182:打开项目...(&O)
00183:关闭项目(&C)
00184:保存项目(&S)
00185:项目另存为...
00186:项目选项...(&P)
00187:选项卡跳转到
00188:书签集
00189:源码跳转到
00190:从项目中删除(&R)
00191:编译结果
00192:警告
00193:错误
00194:主要源码
00195:目标编译
00196:编译时间
00197:打开模板
00198:秒
00199:字节
00200:无法编译 - 程序正在运行
00201:错误
00202:无效的编译器路径。
00203:编译中...
00204:普通文件
00205:模块文件
00206:启动文件
00207:添加文件到项目...(&A)
00208:没有为项目指定主文件。
00209:资源文件
00210:普通
00211:模块
00212:启动
00213:资源
00214:项目选项
00215:新的项目
00216:项目文件
00217:指定的项目路径无效。
00218:（模块级）
00219:最近的项目
00220:编辑技巧
00221:查看函数列表(&F)
00222:只读
00223:函数列表
00224:未找到过程/函数的定义。
00225:清除此列表
00226:常规选项
00227:在选择后关闭函数列表
00228:编译成功
00229:编译失败
00230:执行
00231:头文件
00232:代码文件
00233:启动文件
00234:资源文件
00235:工具提示文字
00236:对齐
00237:显示窗体
00238:边框风格
00239:长度自动化
00240:项目路径
00241:其他选项(32位编译器)
00242:其他选项(64位编译器)
00243:加载HtmlHelp时出错。
00244:找不到帮助文件。
00245:宽度最小化
00246:图片
00247:资源管理器
00248:打开文件
00249:打开项目
00250:显示资源管理器窗口(&E)
00251:显示输出窗口(&T)
00252:编译日志
00253:行
00254:文件
00255:说明
00256:在多个文件中查找
00257:在多个文件中查找...(&I)
00258:搜索子文件夹
00259:文件集
00260:文件夹
00261:选择要搜索的文件夹
00262:搜索结果
00263:TODO
00264:备注
00265:水平间距
00266:另一个应用程序更改了文件，重新加载？
00267:文件已更改
00268:全部重新生成
00269:没有结果
00270:切换替换模式
00271:文件编码
00272:首字母大写
00273:使用命令窗口运行编译程序
00274:退出编辑器前询问
00275:你确定要退出吗？
00276:确认
00277:生成配置...
00278:说明
00279:编译器选项
00280:设为默认值
00281:插入
00282:删除
00283:除选定的生成配置外, 附加指定的编译选项
00284:垂直间距
00285:快速运行(&Q)
00286:本文档已被删除或不再可用。您希望在编辑器中保持文件打开吗？
00287:您确定要删除此编译配置吗？
00288:选项(&O)
00289:用户工具...
00290:工具名称
00291:命令
00292:参数
00293:工作文件夹
00294:快捷键
00295:调用工具时提示确认
00296:最小化运行
00297:等待工具完成，然后再继续
00298:操作：
00299:在编辑器菜单中显示该项
00300:您确定要删除此用户工具吗？
00301:在编译后调用
00302:在预编译期间调用
00303:仅当用户选择时才调用
00304:请确认您希望运行以下用户工具
00305:工具(&T)
00306:行字符长度边界线
00307:位置
00308:创建资源文件和清单
00309:设计器(&D)
00310:新窗体(&N)
00311:显示工具箱(&T)
00312:菜单编辑器...(&M)
00313:工具箱编辑器...(&T)
00314:状态栏编辑器...(&S)
00315:对齐(&A)
00316:左对齐(&L)
00317:水平居中(&C)
00318:右对齐(&R)
00319:顶端对齐(&T)
00320:垂直居中(&M)
00321:底部对齐(&B)
00322:高宽(&S)
00323:同宽(&W)
00324:同高(&H)
00325:高宽相等(&B)
00326:删除(&D)
00327:设计器
00328:代码
00329:等距
00330:增加
00331:减少
00332:窗体内居中(&C)
00333:平铺(&H)
00334:垂直(&V)
00335:锁定控件(&L)
00336:新的主题
00337:主题名称
00338:你确定要删除这个主题吗？
00339:隐藏主工具栏
00340:隐藏主状态栏
00341:用户选择...
00342:粗体
00343:斜体
00344:下划线
00345:操作
00346:导入主题
00347:删除主题
00348:创建新主题
00349:移除
00350:属性
00351:工具
00352:工具箱
00353:事件
00354:关闭其他
00355:关闭左侧标签页
00356:关闭右侧标签页
00357:带标题的菜单项目必须有名称.
00358:菜单项目已跳过一级.
00359:下一个
00360:状态
00361:选中
00362:有效
00363:快捷键
00364:名称
00365:启用对齐线
00366:确定要删除？
00367:菜单名称有重复
00368:图片管理器
00369:添加图片
00370:移除图片
00371:资源格式
00372:附加到控件
00373:与控件解锁
00374:文件类型
00375:大小自动化
00376:实际大小
00377:图片预览
00378:图片集
00379:引用集
00380:添加
00381:宽度
00382:在窗体/代码间切换视图
00383:按钮类型
00384:常规态图片
00385:悬停态图片
00386:禁止态图片
00387:工具链
00388:不使用模板
00389:空白文档
00390:可视化设计器
00391:控制台
00392:Windows DLL
00393:静态库
00394:选项卡配置
00395:选项卡
00396:未选中子窗体

**Comment by PaulSquires** [comment]
Excellent - thanks for sharing the updated Chinese language file. I will include it in version 2.0.4 update.
