### ISSUE TITLE
bug: WinFBE64 Tools button "Open" & "New" 

### ISSUE THREAD

**Issue by lansn** [PaulSquires/WinFBE#13]
Win10 x64,  WinFBE64

When click Toolbar Button "Open" or "New" , the application crashes or throws exceptions.

![QQ图片20200221155416](https://user-images.githubusercontent.com/10512256/75014942-7154e880-54c2-11ea-8b34-39361091f134.png)

**Comment by PaulSquires** [comment]
Thanks for the report. Although the problem does not appear on my computer, I have been able to implement a fix that another user has tested after seeing the same crash on his computer. The fix will be in the version 2.0.6 release. If after using that release you find that the crash still exists then please post back here another bug report. Thanks.
