### ISSUE TITLE
bug : code auto tip Invalid

### ISSUE THREAD

**Issue by lansn** [PaulSquires/WinFBE#14]
frmMain.Text1.Text = "test" 

bug : When open a project first time, auto tip is able, but after add new Text Control or else any Control, then Text1 and Text can not auto tip , Button Control is also , all Controls auto tip are Invalid.

![autotip](https://user-images.githubusercontent.com/10512256/76478464-bfb33280-6443-11ea-895d-c2eeef3bcef3.png)

**Comment by PaulSquires** [comment]
Thanks for the report. I have not been able to reproduce an exact sequence of steps that leads to this bug. I will continue to try to reproduce it. At times in the past I have noticed this type of behaviour but I will be more aware of when the problem occurs and then find a solution. In the meantime, if you can find a distinct sequence of steps that reproduces the problem then please post them here. Step1, Step 2, Step 3, etc...

Thanks

**Comment by lansn** [comment]
Hi, I had tested again,  found the bug occurs on WinFBE64 win10 x64 only, WinFBE32 is ok.

Thanks.

**Comment by lansn** [comment]
test step record:

can not upload the record video, only the .mht file.


[step record.zip](https://github.com/PaulSquires/WinFBE/files/4332182/step.record.zip)

**Comment by PaulSquires** [comment]
Thank-you very much for the additional information. I was finally able to find the source of the problem and fix it. As an added benefit, I was able to refactor a portion of the parser code to make it better especially for displaying codetips. When 2.0.9 is released, if problems still exist with the autocomplete code then please file another bug report. Thanks.
