### ISSUE TITLE
WinFBE 2.0.9 64 bit not using project compiler options

### ISSUE THREAD

**Issue by johnnysmith65** [PaulSquires/WinFBE#16]
I am a first time user of WinFBE and just did a fresh installation of WinFBE 2.0.9 64 bit.  For my project I tried to set the compiler to use -lang fblite by putting -lang fblite in both the the Project->Project Options->Other Options entries and also checking the Options->Build Configurations->Language compatibility check boxes.  Even though this is done, this option is not passed to the compile command line when Compile->Build and Execute is selected.   Ouput is shown below.  It also appears the the default options for the build (i.e. Win64 GUI (Release)) have not been passed (i.e. -s gui).

Failed Compile (Errors 11  Warnings 0  [2020-03-22  04:23:39])

Command Line: 
F:\Files\Programming\WinFBE_Suite\FreeBASIC-1.07.1-gcc-5.2\fbc64.exe  -c -b "C:\Users\Paul\Documents\MP3Read\READMP3_SUBS.bas" -v -o ".\.wfbe\READMP3_SUBS64.o"

FreeBASIC Compiler - Version 1.07.1 (2019-09-27), built for win64 (64bit)
Copyright (C) 2004-2019 The FreeBASIC development team.
standalone
target:       win64, x86-64, 64bit
compiling:    C:\Users\Paul\Documents\MP3Read\READMP3_SUBS.bas -o .\.wfbe\READMP3_SUBS64.c
C:\Users\Paul\Documents\MP3Read\READMP3_SUBS.bas(221) error 148: Suffixes are only valid in -lang deprecated or fblite or qb, found 'string' in 's8 = string$(8,0)'
C:\Users\Paul\Documents\MP3Read\READMP3_SUBS.bas(225) error 148: Suffixes are only valid in -lang deprecated or fblite or qb, found 'str' in 'print

**Comment by PaulSquires** [comment]
Duplicate question responded to in the PlanetSquires support forum. Thanks.
