### ISSUE TITLE
WinFormsX GUI creation plea from visually impaired user

### ISSUE THREAD

**Issue by JanuszChmiel** [PaulSquires/WinFBE#17]
Dear MR Squires,
You are one of The most elite Free Basic programmers. Yours complex and fully functional suite allow professional app creation. You have included The best available libraries for Free Basic.
Because you are experienced programmer, yours soul is full of wisdom.
Do you think, that you would give Me advices how to create GUI by using yours WinFormsX modules without yours professional visual designer?
Before you will close this issue. Please keep in mind, that if you would allow visually impaired developers to create GUi with atleast 3 or 4 various object types, it would allow them to make The joy by others visually impaired people. I do not have ambitions to create extremely graphically attractive GUI. I know, that it is un real. I do not have The ambitions to concurrent other professional absolvents of informatic studies on The world.
My personal dream is to bring visually impaired developers The opportunity to use this modern and very compact language.
Functions and procedures inside WinFormsX requires to specify values in Pixels.
Could you write Me which numbers should I add? If sighted developer will use yours visual designer. Does this tool atuoamtically calculates The values, or sighted programmer uses editable field with Pixel values and he must watch The object position on The screen. So if Pixel value has changed, The object positon value also change on The screen?
I know, that I can not simply ignore The value when calling procedures and functions to create buttons and other GUI elements. Lov level APi calls must contain The value.
The most simplest scenario. One listview, button 1 or 3.
I know, that making automated object oriented Pixels calculations is very complex and require geometry and deep mathematical formulas creation knowledge. I also know, that making such thinks for free is rather science fiction.
But if there is at least a little hope, that you could define a formula for calculationg Pixel position, I will do it on my calculator app to create some GUI.
What do you think about helping not only Me?

I Am ready to test and yours help will not be dropped to zero. And my plea would help others

**Comment by PaulSquires** [comment]
Hi, WinFBE uses the WinFBX library and WinFormsX libraries for GUI code generation. Both libraries are incapable of providing the type of code output and functionality that you desire. Sorry.
