### ISSUE TITLE
Codetips for UDTs only work after loading a file in 64bit editor

### ISSUE THREAD

**Issue by ImortisInglorian** [PaulSquires/WinFBE#19]
[Settings.zip](https://github.com/PaulSquires/WinFBE/files/4599943/Settings.zip)

I included my setting file.

Everything works as expected in 32bit version of IDE.  For 64bit version, if I open a new file and start typing code, the IDE will not provide codetips for UDTs, either as suggesting for variable types after "AS" or with "." and "->" member select operators.

If I open an existing file, all codetips already in the file work, either in a single file or a project, but new UDTs don't give codetips until the file is saved, closed, then re-opened.

**Comment by PaulSquires** [comment]
64-bit translation of the scintilla notification type (SCNotification) was incorrect. It is now fixed and the correct notification is being received. The flag to initiate parsing of the code file is now correctly being set. This issue does not affect the 32-bit version of the editor.
