### ISSUE TITLE
Can't compile WinFBE source code 1.7.4 in WinFBE 1.7.4

### ISSUE THREAD

**Issue by vinodvinu** [PaulSquires/WinFBE#2]
Hi,
Thanks for this superb IDE. I just tried to compile the source code of version 1.7.4 in WinFBE 1.7.4 editor. But it says an error in line number 1271 on WinFBE.bas. Something related to mixing data types.  How to fix this ?

**Comment by PaulSquires** [comment]
WinFBE.bas only has 191 lines... not sure how you can have an error on Line 1271.
Also, make sure that you are compiling WinFBE using the FB compiler (v1.06) that ships with the WinFBE_Suite.rar package. That compiler does not generate warnings for mixing boolean data types.

I compile WinFBE using WinFBE all the time with no trouble. Using the WinFBE_Suite install I am guaranteed to have the correct WinFBE support files available (FB compiler and WinFBX library).

**Comment by PaulSquires** [comment]
Issue closed.
