### ISSUE TITLE
bug: clipboard Cut in Toolbox|Properties field irreversably cuts control from form client area

### ISSUE THREAD

**Issue by ssepan2** [PaulSquires/WinFBE#21]
RECREATE:
In form designer, put control on form (one with Name, Text, Tooltip fields that you might edit). With control selected, go to Toolbox window, and Properties tab. Highlight some portion of text in one property (with intention to move to another property), press Ctrl-X to Cut.
ERROR:
Text in property is not Cut. Control is Cut from form. Ctrl-Z (undo) and Ctrl-V (paste) will not restore.
EXPECTED:
Text in property is Cut.
WORKAROUND:
(If control previously saved) Immediately close project and do not save changes. Lose recent edits but not any controls prior to last save.
VERSION:
2.1.8
OPINION:
Related to #25
IDE main window is seeing/responding to keystrokes while focus is in Toolbox window.

**Comment by PaulSquires** [comment]
Select All and Cut actions were not acting on the correct focused area of the visual designer. This has been corrected by explicitly testing for edit focus of the embedded textbox control within the PropertyList dialog.
