### ISSUE TITLE
bug: clipboard Select All (Ctrl-A) in Replace dialog field selects all code in code window

### ISSUE THREAD

**Issue by ssepan2** [PaulSquires/WinFBE#25]
RECREATE:
In code window, highlight a section of code with the intention to replace in selection. With code selected, go to Replace dialog (Ctrl-R), and edit Find, Replace fields. Decide to select all text in field press Ctrl-A to Select All.
ERROR:
Text in field is not selected. Selection of code in code window is expanded to all code. 
EXPECTED:
Text in field is selected (all text). Code selection does not change.
WORKAROUND:
Must return to code window and re-apply desired selection.
VERSION:
2.1.8
OPINION:
Related to #21
IDE main window is seeing/responding to keystrokes while focus is in Replace dialog.

**Comment by PaulSquires** [comment]
Extra code added to check if either of the textboxes in the find/replace dialog has focus. If yes, then the text in that textbox will be fully selected rather than the underlying active code editing window.
