### ISSUE TITLE
bug: Replace All sometimes skips last item

### ISSUE THREAD

**Issue by ghost** [PaulSquires/WinFBE#29]
RECREATE:
This one is harder to mail down. Was able to recreate with scenario involving multiple replaces in a selection. Only happened on subsequent (2nd) replacement, but not 3rd (maybe just because of the following steps), and the 2nd replacement involved: editing the Replace field with a variation of the first replacement, then changing the Find, and finally firing the Replace All in the selection. (Update: saw it happen when editing the Find field but NOT the Replace field, so scenario is not solid.)
ERROR:
All replace targets are replaced except the last in the selection. Replace dialog shows 1 more candidate found, and clicking Replace All again changes the remaining item.
EXPECTED:
All found items are replaced with a single click of Replace All button.
WORKAROUND:
If one is missed, click the Replace All button a 2nd time, and it will get the last time too.
VERSION:
2.1.8

**Comment by mantispool** [comment]
The source of this error has been fixed and will be in the next update release (version 3.0.0). Thanks!

**Comment by PaulSquires** [comment]
The source of this error has been fixed and will be in the next update release (version 3.0.0). Thanks!
