### ISSUE TITLE
bug: WinFBE64 will be crash when open the \SourceCode\WinFBE.wfbe

### ISSUE THREAD

**Issue by lansn** [PaulSquires/WinFBE#30]
WinFBE64 will be crash when open the \SourceCode\WinFBE.wfbe, but WinFBE32 is OK. Maybe  can not open many files at the same time.
-------------
win10 x64 professional  winfbe 2.1.9，2.2.0

**Comment by PaulSquires** [comment]
I have found a source for GPF crash when loading files (array index out of bounds) that seems to manifest itself more so on WinFBE 64-bit so this could very well be the crash that you have reported. The fix will be in the upcoming WinFBE Version 3 update.
