### ISSUE TITLE
v3:  where is the toolbox ?

### ISSUE THREAD

**Issue by lansn** [PaulSquires/WinFBE#34]
Where is the toolbox ?  I like the toolbox of v2

**Comment by PaulSquires** [comment]
Toolbox has not changed between V2 and V3. I assume that you mean the Toolbar. The Toolbar has been removed and will not be re-implemented. This is similar to the user interface of Visual Studio Code.

**Comment by lansn** [comment]
Yes, I mean it's a pity that toolbar had been removed from v3. 
![toolbar](https://user-images.githubusercontent.com/10512256/170159850-5c21f767-b397-4b58-ba40-6dc442fdb1c3.png)
I like the complie build button, and toggle win32 console, win32 gui, and so on very much.
 I'm looking forward to improving the forme design and event code auto generation
