### ISSUE TITLE
Forum upgrade

### ISSUE THREAD

**Issue by JoseRoca** [PaulSquires/WinFBE#35]
After the forum upgrade, I no longer can access the PlanetSquires forum. It says that the user name does not exist.

**Comment by PaulSquires** [comment]
Thanks José, there was an issue with the conversion of the accent in your name so I had to reset your user name to José Roca manually. Doing this automatically resets your forum password so you should check your gmail for an email that was generated by the SMF software. If you do not get it then please let me know.
