### ISSUE TITLE
bug: bas file had been closed, open it again button click function will be  Duplicated definition

### ISSUE THREAD

**Issue by lansn** [PaulSquires/WinFBE#38]
winfbe 3.0.3
1, bas file had been closed, open it again button click function will be  Duplicated definition
2. when i set the file character encoding is utf-8 bom, next time reopen the bas file, the character encoding auto set ansi

Application.Run(Form1)

''
''
Function Form1_Button1_Click( ByRef sender As wfxButton, ByRef e As EventArgs ) As LRESULT
   form1.Text1.Text="hekloé‹è®©ä»–å¤©å¤©"
   Function = 0
End Function

''
''
Function Form1_Button2_Click( ByRef sender As wfxButton, ByRef e As EventArgs ) As LRESULT
   form1.Text1.Text="tttt2å°±å°†è®¡å°±è®¡"
   Function = 0
End Function''
''
Function Form1_Button1_Click( ByRef sender As wfxButton, ByRef e As EventArgs ) As LRESULT
   Function = 0
End Function

''
''
Function Form1_Button2_Click( ByRef sender As wfxButton, ByRef e As EventArgs ) As LRESULT
   Function = 0
End Function

**Comment by PaulSquires** [comment]
Thank you for the bug report. I have fixed the Form file encoding being reset to ANSI and the fix will be in version 3.0.4.
When you test that version, please also confirm whether the duplicate event issue you experienced has also disappeared.

**Comment by lansn** [comment]
winfbe 3.0.4
1,  .bas source file had been closed, open it again button click function will be Duplicated definition.
**the bug is not fixed yet**
----------------------------------
Function Form1_Button1_Click( ByRef sender As wfxButton, ByRef e As EventArgs ) As LRESULT
Function = 0
End Function

''
''
Function Form1_Button1_Click( ByRef sender As wfxButton, ByRef e As EventArgs ) As LRESULT
Function = 0
End Function

''
Function Form1_Button1_Click( ByRef sender As wfxButton, ByRef e As EventArgs ) As LRESULT
Function = 0
End Function

**Comment by PaulSquires** [comment]
Thanks, I had been testing for the bug in forms existing within a Project. Looks like the bug happens when you are using the visual designer outside of a Project. This should be an easy bug to fix and I will upload a new version as soon as the bug is corrected.

**Comment by PaulSquires** [comment]
I believe that this issue should now be fixed. Please download and try version 3.0.5. If the issue still persists for you then please let me know so that I can do further investigation. Thanks!
