### ISSUE TITLE
Crash when Ctrl+S or F12 is pressed when no file is open

### ISSUE THREAD

**Issue by lwchkg** [PaulSquires/WinFBE#39]
Steps to reproduce:
1. Start WinFBE
2. Close all files (if any is open)
3. Press Ctrl + S or F12.

Expected behavior:
Nothing happens. Maybe a beep sound for failure to execute command.

Actual behavior:
Crash.

**Comment by PaulSquires** [comment]
Thank you for the bug report. This bug is now fixed and will be included in the version 3.0.4 update.
