### ISSUE TITLE
Maximum Numer Of Characters In TextBox

### ISSUE THREAD

**Issue by Hoffenbar** [PaulSquires/WinFBE#7]
Regardless of what combination of properties I configure (MaxLength 32000), I never can enter more characters (lines) in the textbox than possible within the visible view. No scrolling happens. There must be something that I missed.....

**Comment by Hoffenbar** [comment]
An addition: In the last visible line, nothing happens if i press enter...

**Comment by PaulSquires** [comment]
- Fixed: TextBox. Added ES_AUTOVSCROLL for multiline textboxes when AcceptReturn = True. 

You will need to download the latest WinFormsX code files from https://github.com/PaulSquires/WinFormsX and overwrite the ones that ship in WinFBE ( \WinFBE_Suite\FreeBASIC-1.06.0\inc\WinFormsX )

When you load your project, ensure that the TextBox property "AcceptsReturn" is set to true. The code generation may not be triggered so change a couple of properties or move the control on the form to ensure that the Form gets saved and code gets regenerated.

**Comment by PaulSquires** [comment]
Closed
